### ISSUE TITLE
Missing license.

### ISSUE THREAD

**Issue by Wesztman** [bigjosh/Quadrature#1]
Hi Josh!

Love your work on this, I would really like to use this for a project of mine.

But since the repo is missing a license I can't (at least with a clean conscience).

Would u like to add a license to the repo? 😊

Kind Regards
Carl

**Comment by bigjosh** [comment]
I just added MIT. Good enough for your purposes? What are your purposes? :)

-josh

**Comment by Wesztman** [comment]
That is perfect, thanks! 😄 I'm trying to build a fake encoder for black-box testing of a PLC 😊
